variable "tenant" {}
variable "name" {}
variable "environment" {}
variable "encryption" {}
variable "kms_key_id" {}
variable "table_name" {}
variable "hash_key" {}
variable "range_key" {}
variable "billing_mode" {}
variable "table_class" {}
variable "deletion_protection" {}
variable "point_in_time_recovery" {}
variable "ttl_enabled" {}
variable "ttl_attribute_name" {}
variable "attributes" {}
variable "global_secondary_indexes" {}
variable "local_secondary_indexes" {}